In [1]:
!pip install numba

In [2]:
import numpy as np
from numba import cuda

# Matrix dimensions
N = 1024
scalar = 10

# Input matrix
A = np.random.randint(0, 100, (N, N)).astype(np.float32)

# Output matrix
C = np.zeros_like(A)

# CUDA Kernel
@cuda.jit
def scalar_add_kernel(A, scalar, C):

    row, col = cuda.grid(2)

    if row < A.shape[0] and col < A.shape[1]:
        C[row, col] = A[row, col] + scalar

# Threads and blocks
threads_per_block = (16, 16)

blocks_x = (N + threads_per_block[0] - 1) // threads_per_block[0]
blocks_y = (N + threads_per_block[1] - 1) // threads_per_block[1]

blocks_per_grid = (blocks_x, blocks_y)

# Launch Kernel
scalar_add_kernel[blocks_per_grid, threads_per_block](A, scalar, C)

cuda.synchronize()

print("Input Matrix Sample:")
print(A[:5,:5])

print("\nOutput Matrix Sample:")
print(C[:5,:5])

Input Matrix Sample:
[[88. 43. 70. 14. 24.]
 [71. 88. 27. 65. 60.]
 [81. 68. 71. 69. 25.]
 [87. 71. 35. 66. 44.]
 [80. 95. 32. 20. 97.]]

Output Matrix Sample:
[[ 98.  53.  80.  24.  34.]
 [ 81.  98.  37.  75.  70.]
 [ 91.  78.  81.  79.  35.]
 [ 97.  81.  45.  76.  54.]
 [ 90. 105.  42.  30. 107.]]


/usr/local/lib/python3.12/dist-packages/numba_cuda/numba/cuda/cudadrv/devicearray.py:934: NumbaPerformanceWarning: Host array used in CUDA kernel will incur copy overhead to/from device.
  warn(NumbaPerformanceWarning(msg))
